### ISSUE TITLE
Base de Datos SQL Server

### ISSUE THREAD

**Issue by marlujo1509** [artie-labs/transfer#159]
Muy buenos dias,
Como se puede trabajar Artie con bases de datos Microsoft SQL Server?

**Comment by Tang8330** [comment]
Hi @marlujo1509! Microsoft SQL server should be easy to support since Debezium [already integrates with it](https://debezium.io/documentation/reference/stable/connectors/sqlserver.html).

We'll add this to the backlog, if you need this sooner - get in touch with us at [hi@artie.so](mailto:hi@artie.so)!

**Comment by Tang8330** [comment]
Hey @marlujo1509 - we've just implemented SQL Server as a destination, PR: https://github.com/artie-labs/transfer/pull/355
